[package]
name = "whisper_volume"
version = "0.1.0"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2"
rand = "0.3"

[lib]
name = "whisper"
crate-type = ["cdylib"]
